### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ncannasse** [ncannasse/hlos#1]
These are various tasks that could be done to improve further the HLOS:
- [x] implement setjmp/longjmp (exceptions)
- [x] custom memory allocator with OS memory mapping
- [ ] implement free() + separate big pages from small blocks
- [ ] implement math functions
- [x] allow to set native functions from Haxe code (math etc.)
- [x] complete keyboard support
- [x] complete mouse support
- [x] allow to use BIOS interrupts (switch VGA mode etc.)
- [ ] network support + implement IP/UDP/TCP stack
- [ ] hdd support + FAT32 system + MBR
- [ ] date and time
- [ ] sound
- [x] allow a 3rd party bootloader such as Limine or GRUB, so it can boot on ISO/USB/UEFI

**Comment by Matvii-Jarosh** [comment]
I would say that if this project had developed, I would have switched to this operating system, it’s just a pity to see that such a good programming language (~~as2~~ haxe) is almost always used only for games. I just now have a framework for creating servers on hashlink which can already be shown to the public, but this is pointless, no one will use haxe/hashlink for the server part, no one needs a good GUI for desktop programs, no one needs mobile applications on haxe, everyone just Need replacement JS and games. That's why I have to write everything in C++. I like haxe better, but no one needs it to create a server part or GUI applications, especially for an operating system, so what can I say, haxe and hashlink were created for game development (I think so). I know that you can write almost anything you want in any language, but the point is that it is not presented as a language for anything other than libraries and games. I hope you understand me
